/*
 * This source file was generated by the Gradle 'init' task
 */
package coding;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    @Test
    void appHasAGreeting() {
        Athlete athlete = new Athlete("adrian", 20, 80, 176);
        assertEquals(20, athlete.getAge(), "Age should be 20");
    }
}
